/**
 * Engine orchestrator — main entrypoint for programmatic generation.
 *
 * Pipeline:
 *   1. Build combos (services × locations, cap'd by maxPages)
 *   2. Call slotProvider for each kept combo (parallel)
 *   3. Per-page lint (word count, required elements)
 *   4. Cross-page similarity check
 *   5. Aggregate to GenerateOutput with pages/failed/issues split
 *
 * The engine is PURE: no file I/O, no network. Caller is responsible for:
 *   - Writing pages to disk
 *   - Providing slot content (manual / AI / hybrid)
 *   - Deciding what to do with `failed` (block build vs warn)
 */

import { buildCombos, findDuplicateSlugs } from "./combos.js";
import { lintPage } from "./quality.js";
import { pairwiseSimilarity, type SimilarityPair } from "./similarity.js";
import {
  DEFAULT_THRESHOLDS,
  type GenerateInput,
  type GenerateOutput,
  type PageOutput,
  type QualityIssue,
  type QualityThresholds,
} from "./types.js";

export async function generateProgrammaticPages(input: GenerateInput): Promise<GenerateOutput> {
  const thresholds = mergeThresholds(input.thresholds);

  // 1. Combos
  const { selected, cappedOut } = buildCombos({
    services: input.services,
    locations: input.locations,
    maxPages: thresholds.maxPages,
    ...(input.basePath !== undefined && { basePath: input.basePath }),
  });

  // 2. Duplicate slug check (rare but possible if two locations slugify to same value)
  const duplicates = findDuplicateSlugs(selected);

  // 3. Call slot provider for each combo (parallel)
  const slotPromises = selected.map(async (combo) => {
    const slots = await input.slotProvider(combo);
    return { combo, slots };
  });
  const built = await Promise.all(slotPromises);

  // 4. Per-page lint
  const lintedPages: PageOutput[] = built.map(({ combo, slots }) => {
    const { issues, wordCount } = lintPage({
      slug: combo.slug,
      slots,
      thresholds,
    });
    return {
      slug: combo.slug,
      combo,
      slots,
      wordCount,
      similarPages: [],
      issues,
    };
  });

  // 5. Mark duplicate slugs as errors
  for (const dup of duplicates) {
    for (const page of lintedPages) {
      if (page.slug === dup) {
        page.issues = [
          ...page.issues,
          {
            pageSlug: page.slug,
            severity: "error",
            code: "duplicate_slug",
            message: `Slug "${page.slug}" is generated by multiple combos — slugify collision`,
          },
        ];
      }
    }
  }

  // 6. Cross-page similarity
  const similarityPairs = pairwiseSimilarity(
    lintedPages.map((p) => ({ slug: p.slug, text: p.slots.body })),
  );

  attachSimilarityToPages(lintedPages, similarityPairs, thresholds.maxSimilarityRatio);

  // 7. Split into passed/failed
  const failed = lintedPages.filter((p) => p.issues.some((i) => i.severity === "error"));
  const passed = lintedPages.filter((p) => !p.issues.some((i) => i.severity === "error"));

  const allIssues: QualityIssue[] = lintedPages.flatMap((p) => p.issues);

  return {
    pages: passed,
    failed,
    allIssues,
    cappedOut,
    thresholds,
  };
}

function mergeThresholds(overrides?: Partial<QualityThresholds>): QualityThresholds {
  return { ...DEFAULT_THRESHOLDS, ...overrides };
}

function attachSimilarityToPages(
  pages: PageOutput[],
  pairs: ReadonlyArray<SimilarityPair>,
  maxRatio: number,
): void {
  const bySlug = new Map<string, Array<{ slug: string; ratio: number }>>();
  for (const page of pages) bySlug.set(page.slug, []);

  for (const pair of pairs) {
    bySlug.get(pair.slugA)?.push({ slug: pair.slugB, ratio: pair.ratio });
    bySlug.get(pair.slugB)?.push({ slug: pair.slugA, ratio: pair.ratio });
  }

  for (const page of pages) {
    const list = bySlug.get(page.slug) ?? [];
    list.sort((a, b) => b.ratio - a.ratio);
    page.similarPages = list.slice(0, 3);

    // Add issues for pages exceeding similarity threshold
    for (const peer of page.similarPages) {
      if (peer.ratio > maxRatio) {
        page.issues = [
          ...page.issues,
          {
            pageSlug: page.slug,
            severity: "error",
            code: "similarity_too_high",
            message: `Page is ${(peer.ratio * 100).toFixed(0)}% similar to ${peer.slug} (max ${(maxRatio * 100).toFixed(0)}%)`,
            data: { ratio: peer.ratio, threshold: maxRatio, peer: peer.slug },
          },
        ];
      }
    }
  }
}
