/**
 * Demo client config — "Ślusarz Kowalski Rzeszów".
 *
 * In production, this file is generated by the onboarding wizard / provisioning workflow
 * and committed to each klient's repo. Editing locally is for development/preview only.
 */

import { validateClientConfig, type ClientConfig } from "./client.config.schema.js";

const config: ClientConfig = {
  clientId: "clk_kowalski_rzeszow",

  business: {
    name: "Ślusarz Kowalski",
    legalName: "Kowalski Jan — Usługi Ślusarskie",
    nip: "8121234567",
    regon: "123456789",
    industry: "locksmith",
    schemaType: "Locksmith",
    foundedYear: 2005,
    employeeCount: 3,
    description:
      "Profesjonalne usługi ślusarskie w Rzeszowie. Otwieranie zamków, dorabianie kluczy, naprawa drzwi — 24/7.",
    tagline: "Otworzymy każdy zamek — 24/7 w Rzeszowie i okolicach",
    longDescription:
      "Działam jako ślusarz w Rzeszowie od ponad 20 lat. Specjalizuję się w awaryjnym otwieraniu zamków, dorabianiu kluczy do drzwi, samochodów i mebli oraz montażu nowoczesnych systemów zabezpieczeń. Pracuję na całe Podkarpacie, dojazd zwykle w ciągu 30 minut. Wszystkie usługi wykonuję bez uszkodzenia drzwi — to moja gwarancja.",
  },

  contact: {
    primaryPhone: "+48171234567",
    email: "kontakt@kowalski-slusarz.pl",
    notificationEmail: "kontakt@kowalski-slusarz.pl",
    contactPersonName: "Jan Kowalski",
  },

  location: {
    address: {
      streetAddress: "ul. Słowackiego 12",
      city: "Rzeszów",
      voivodeship: "podkarpackie",
      postalCode: "35-060",
      country: "PL",
    },
    geo: {
      latitude: 50.0413,
      longitude: 21.999,
    },
    serviceArea: ["Rzeszów", "Boguchwała", "Tyczyn", "Łańcut", "Krasne", "Świlcza"],
  },

  services: [
    {
      slug: "awaryjne-otwieranie-zamkow",
      name: "Awaryjne otwieranie zamków",
      description:
        "Otwieram każdy zamek w drzwiach, oknach i samochodach bez uszkodzenia. Dojazd 24/7.",
      priceFrom: "od 100 zł",
      iconKey: "key",
    },
    {
      slug: "dorabianie-kluczy",
      name: "Dorabianie kluczy",
      description:
        "Dorabiam klucze do drzwi, kłódek, mebli i samochodów. Pełen zestaw + transponder.",
      priceFrom: "od 30 zł",
      iconKey: "duplicate",
    },
    {
      slug: "wymiana-zamkow",
      name: "Wymiana zamków",
      description:
        "Wymiana wkładek, klamek, montaż nowych zamków klasy B/C/C+ w drzwiach mieszkaniowych i lokalowych.",
      priceFrom: "od 200 zł",
      iconKey: "shield",
    },
    {
      slug: "naprawa-drzwi",
      name: "Naprawa drzwi",
      description:
        "Regulacja zawiasów, wymiana zamków, naprawa po włamaniu, montaż wzmocnień antywłamaniowych.",
      priceFrom: "wycena indywidualna",
      iconKey: "wrench",
    },
    {
      slug: "systemy-zabezpieczen",
      name: "Systemy zabezpieczeń",
      description:
        "Montaż zamków elektronicznych, certyfikowanych wkładek, drzwi antywłamaniowych.",
      priceFrom: "od 500 zł",
      iconKey: "lock",
    },
  ],

  hours: {
    monday: ["08:00", "18:00"],
    tuesday: ["08:00", "18:00"],
    wednesday: ["08:00", "18:00"],
    thursday: ["08:00", "18:00"],
    friday: ["08:00", "18:00"],
    saturday: ["09:00", "14:00"],
    sunday: "closed",
    note: "Awaryjne wezwania 24/7 — telefon w każdej chwili",
  },

  theme: {
    preset: "craftsman",
    variant: "red-bold",
  },

  domain: {
    primary: "kowalski-slusarz.pl",
    canonicalScheme: "https",
  },

  integrations: {
    plausible: true,
    zaraz: false,
  },

  reviews: [
    {
      author: "Anna M.",
      rating: 5,
      date: "2026-03-12",
      text:
        "Przyjechał w środku nocy po wyważeniu drzwi. Otworzył zamek w 5 minut, bez uszkodzenia. Cena uczciwa, polecam.",
      source: "gbp",
    },
    {
      author: "Marek T.",
      rating: 5,
      date: "2026-02-28",
      text: "Dorobił klucz do starych drzwi z lat 70. Inne firmy odmówiły, on zrobił w 30 minut.",
      source: "gbp",
    },
    {
      author: "Beata K.",
      rating: 5,
      date: "2026-01-15",
      text: "Profesjonalna wymiana zamków po włamaniu. Doradził rozwiązania, zamontował tego samego dnia.",
      source: "gbp",
    },
  ],

  rodo: {
    consentVersion: "v1.0",
    privacyPolicyUrl: "https://kowalski-slusarz.pl/polityka-prywatnosci",
    termsUrl: "https://kowalski-slusarz.pl/regulamin",
    dpaSigned: true,
  },
};

// Validate at module-load. Throws on bad config — fails Astro build.
export default validateClientConfig(config);
